# Configuration pour l'ETF personnalisé

# Paramètres généraux de l'ETF
etf:
  name: "Innovation Tech Émergente ETF"
  description: "ETF focalisant sur les entreprises technologiques dans des marchés émergents spécifiques"
  benchmark: "MSCI Emerging Markets Technology Index"
  inception_date: "2023-01-01"
  rebalancing:
    frequency: "quarterly"  # Options: monthly, quarterly, semi-annually, annually
    threshold: 0.05  # Seuil de déviation pour le rebalancement conditionnel (5%)
  management_fee: 0.0065  # 0.65% par an
  tracking_error_target: 0.02  # 2% maximum

# Critères de sélection des actifs
asset_selection:
  markets:
    - "Brazil"
    - "Russia"
    - "India"
    - "China"
    - "South Africa"
    - "Mexico"
    - "Indonesia"
    - "Turkey"
  sectors:
    - "Technology"
    - "Telecommunications"
    - "Consumer Electronics"
    - "Fintech"
    - "E-commerce"
  filters:
    min_market_cap: 500000000  # 500M USD minimum
    min_daily_volume: 1000000  # 1M USD minimum daily trading volume
    max_volatility: 0.4  # 40% volatilité annualisée maximum
    min_profit_margin: 0.05  # 5% minimum
    max_debt_to_equity: 2.0  # Ratio dette/fonds propres maximum
    esg_minimum_score: 50  # Score ESG minimum (échelle 0-100)

# Méthode de pondération
weighting:
  method: "smart_beta"  # Options: market_cap, equal_weight, smart_beta, fundamental
  smart_beta:
    factors:
      - name: "momentum"
        weight: 0.25
      - name: "value"
        weight: 0.25
      - name: "quality"
        weight: 0.25
      - name: "low_volatility"
        weight: 0.25
  constraints:
    max_weight_per_asset: 0.10  # Maximum 10% par actif
    max_weight_per_country: 0.35  # Maximum 35% par pays
    max_weight_per_sector: 0.40  # Maximum 40% par secteur

# Sources de données
data_sources:
  market_data: "yahoo_finance"  # Options: yahoo_finance, alpha_vantage, quandl
  fundamental_data: "simfin"  # Options: simfin, alpha_vantage
  esg_data: "refinitiv"  # Options: refinitiv, msci, sustainalytics
  api_keys:
    alpha_vantage: "${ALPHA_VANTAGE_API_KEY}"
    quandl: "${QUANDL_API_KEY}"
    simfin: "${SIMFIN_API_KEY}"

# Paramètres de backtesting
backtesting:
  start_date: "2018-01-01"
  end_date: "2022-12-31"
  initial_capital: 10000000  # 10M USD
  include_transaction_costs: true
  transaction_cost_model: "percentage"  # Options: percentage, fixed
  bid_ask_spread: 0.001  # 10 points de base
  broker_commission: 0.0002  # 2 points de base

# Paramètres d'analyse du risque
risk_analysis:
  risk_free_rate: 0.02  # 2% annualisé
  confidence_level: 0.95  # Pour les calculs de VaR
  metrics:
    - "sharpe_ratio"
    - "sortino_ratio"
    - "maximum_drawdown"
    - "tracking_error"
    - "information_ratio"
    - "value_at_risk"
    - "expected_shortfall"
    - "beta"
    - "alpha"

# Paramètres de rapports
reporting:
  frequency: "monthly"  # Options: daily, weekly, monthly, quarterly
  include_charts: true
  include_attribution_analysis: true
  output_formats:
    - "pdf"
    - "html"
    - "json"